#!/bin/sh

id="${1:-0}"
dir="/sys/class/power_supply/BAT$id"

test -d "$dir" || exit 1

read -r state < "$dir/status"
read -r percentage < "$dir/capacity"

if test $percentage -ge 90; then
    icon=
elif test $percentage -ge 65; then
    icon=
elif test $percentage -ge 40; then
    icon=
elif test $percentage -ge 15; then
    icon=
elif test $percentage -ge 1; then
    icon=
fi

test "$state" = "Charging" && icon=

echo "$icon $percentage%"
