#!/bin/sh

# reterieve a bibtex entry from a DOI

doi2bib() {
    curl -s -q -L -H "Accept: application/x-bibtex" https://doi.org/"$1"
}

if test $# -eq 0; then
    while read -r line; do
        doi2bib "$line"
    done
    exit 0
fi

for doi; do
    doi2bib "$doi"
done
