#!/bin/sh
#exec w3m "duckduckgo.com/lite?kd=-1&kp=-1&q=$*"
#exec lynx "https://lite.duckduckgo.com/lite?kd=-1&kp=-1&q=$(urlencode $*)" # 🦆
#exec lynx "duckduckgo.com/lite?q=$*" # 🦆
#exec w3m "duckduckgo.com/lite?q=$*"
exec w3m "duckduckgo.com/lite?q=$(urlencode -s $*)"
