#!/bin/sh

if command -v xclip > /dev/null 2>&1; then
    # rmlastnl remove the newline at the end.
    exec xclip -out -selection clipboard -rmlastnl
elif command -v xsel > /dev/null 2>&1; then
    exec xsel --output --clipboard
else
    echo "xclip and xsel are not found." 2>&1
fi
