#!/bin/sh

if test -n "$WAYLAND_DISPLAY"; then
    wl-paste
elif test -n "$DISPLAY"; then
    xclip -out -selection clipboard -rmlastnl || \
        xsel --output --clipboard
else
    cat /tmp/clip
fi
