#!/bin/sh

# a wrapper script around [tgpt](https://specifications.freedesktop.org/basedir-spec/latest/).

provider="duckduckgo"

gpt() {
    exec tgpt --quiet --whole --provider "$provider" "$*" 2>/dev/null
}

if ! command -v tgpt >/dev/null; then
    echo "cmd does not exist: tgpt" 1>&2
    exit 1
fi

if test $# = 0; then
    gpt < /dev/stdin
    exit 0
fi

gpt "$*"
