#!/bin/sh

manpath='/usr/bin/man'

# bold
export LESS_TERMCAP_md=$'\033[93m'
export LESS_TERMCAP_me=$'\033[0m'
# underline
export LESS_TERMCAP_us=$'\033[10;32m'
export LESS_TERMCAP_ue=$'\033[0m'
# idk 🐸
export LESS_TERMCAP_so=$'\033[35;40m'
export LESS_TERMCAP_se=$'\033[0m'

test $# -ne 0 && exec $manpath "$@"
