#!/bin/sh

term="lxterminal"
font="Monospace 13"
cols="72"
rows="29"

lxterminal() {
	exec lxterminal --geometry="${cols}x${rows}"
}

sakura() {
	exec sakura -f "$font" -c "$cols" -r "$rows"
}

"$term"
