#!/bin/bash

# just a password generator 0_0...
# this is faster anyway...
# head -n 25 /dev/random | tr -dc '[:graph:]' | cut -c -24

if [[ -z $1 ]]; then
    read -p "password length (default is 24 characters): " length
    length=${length:-24}
else
    length=$1
fi

while read -r line; do
    garbage="$garbage $line"
    (( lines++ ))
    (( lines >= 5 )) && break
done < /dev/random

long_string="$(tr -cd "[:graph:]" <<< $garbage)"

echo "${long_string:0:${length}}"
