#!/bin/sh
#QUTE_URL: hint link from qutebrowser -_-
Url="$1"

{ 
    ! [ -d "/tmp/qutube" ] && mkdir -p /tmp/qutube --mode 700
    title=$(yt-dlp --print title "$Url" 2> /dev/null) && \
        yt-dlp --print description "$Url" > /tmp/qutube/${title}.txt
    } & 

quality=$(printf '144\n240\n360\n480\n720\n1080\naudio' | dmenu -i -p "quality: ") || exit 0

if [ "$quality" = "audio" ]; then
    exec mpv --ytdl-format="bestaudio" "$Url"
else
    exec mpv --ytdl-format="bestvideo[height=${quality}]+bestaudio/bestvideo[height=360]+bestaudio/best" "$Url" 
fi

