#!/bin/sh

# TODO: add X11 support
# TODO: this only works on sway -_-

# screenshots scripts

dir="$HOME/shots"
id=$(date "+%Y%m%dT%H%M%S")

shot_screen() {
    grim "$dir/$id.png"
}

shot_window() {
    swaymsg -t get_tree \
        | jq -r '.. | select(.focused?) | .rect | "\(.x),\(.y) \(.width)x\(.height)"' \
        | grim -g - "$dir/$id.png"
}

test -d "$dir" || mkdir "$dir"

case "$1" in
    win*) shot_window;;
    *) shot_screen;;
esac
