#!/bin/bash

declare -A theme_gruvbox=([background]="#282828" [foreground]="#ebdbb2"
[cursorColor]="#ebdbb2" [0]="#282828" [1]="#cc241d" [2]="#98971a"
[3]="#d79921" [4]="#458588" [5]="#b16286" [6]="#689d6a" [7]="#a89984"
[8]="#928374" [9]="#fb4934" [10]="#b8bb26" [11]="#fabd2f" [12]="#83a598"
[13]="#d3869b" [14]="#8ec07c" [15]="#ebdbb2")

declare -A theme_papercolor=([background]="#eeeeee"
[foreground]="#444444" [cursorColor]="#444444" [0]="#eeeeee"
[1]="#af0000" [2]="#008700" [3]="#5f8700" [4]="#0087af" [5]="#878787"
[6]="#005f87" [7]="#444444" [8]="#bcbcbc" [9]="#d70000" [10]="#d70087"
[11]="#8700af" [12]="#d75f00" [13]="#d75f00" [14]="#005faf"
[15]="#005f87")

declare -A theme_solarized=([background]="#002b36"
[foreground]="#839496" [cursorColor]="#93a1a1" [0]="#073642"
[1]="#dc322f" [2]="#859900" [3]="#b58900" [4]="#268bd2" [5]="#d33682"
[6]="#2aa198" [7]="#eee8d5" [8]="#002b36" [9]="#cb4b16" [10]="#586e75"
[11]="#657b83" [12]="#839496" [13]="#6c71c4" [14]="#93a1a1"
[15]="#fdf6e3")

declare -A theme_nord=([foreground]="#D8DEE9" [background]="#2E3440"
[cursorColor]="#D8DEE9" [0]="#3B4252" [1]="#BF616A" [2]="#A3BE8C"
[3]="#EBCB8B" [4]="#81A1C1" [5]="#B48EAD" [6]="#88C0D0" [7]="#E5E9F0"
[8]="#4C566A" [9]="#BF616A" [10]="#A3BE8C" [11]="#EBCB8B" [12]="#81A1C1"
[13]="#B48EAD" [14]="#8FBCBB" [15]="#ECEFF4")

declare -A theme_acme=([background]="#FFFFEA" [foreground]="#000000"
[cursorColor]="#444444" [0]="#eeeeee" [1]="#af0000" [2]="#008700"
[3]="#5f8700" [4]="#0087af" [5]="#878787" [6]="#005f87" [7]="#444444"
[8]="#bcbcbc" [9]="#d70000" [10]="#d70087" [11]="#8700af" [12]="#d75f00"
[13]="#d75f00" [14]="#005faf" [15]="#005f87")

declare -A theme_onedark=([foreground]="#ABB2BF" [background]="#282C34"
[cursorColor]="#ABB2BF" [0]="#2C323C" [8]="#3E4452" [1]="#E06C75"
[9]="#E06C75" [2]="#98C379" [10]="#98C379" [3]="#E5C07B" [11]="#E5C07B"
[4]="#61AFEF" [12]="#61AFEF" [5]="#C678DD" [13]="#C678DD" [6]="#56B6C2"
[14]="#56B6C2" [7]="#5C6370" [15]="#ABB2BF")

declare -A theme_rosepine=([foreground]="#e0def4"
[background]="#191724" [cursorColor]="#e0def4" [0]="#1f1d2e"
[8]="#26233a" [1]="#eb6f92" [9]="#eb6f92" [2]="#f6c177" [10]="#f6c177"
[3]="#ebbcba" [11]="#ebbcba" [4]="#31748f" [12]="#31748f" [5]="#c4a7e7"
[13]="#c4a7e7" [6]="#9ccfd8" [14]="#9ccfd8" [7]="#6e6a86"
[15]="#908caa")

set_vim_colors() {
    sed -i --follow-symlinks -E "
    s/set (bg|background).*/set \1=$vim_bg/;
    s/(colo|colorscheme) .*/\1 $vim_colorscheme/
    " "$HOME/.vimrc" "$HOME/.vim/set_colors.vim"

    # make sure to have SigUSR1 autocmd in your vimrc
    pkill -10 vim
}

set_i3_colors() {
    sed -i --follow-symlinks -E "
    s/set .bar_bg.*/set \\\$bar_bg $bar_bg/;
    s/set .bar_fg.*/set \\\$bar_fg $bar_fg/;
    " "$HOME/.config/i3/config"

    i3-msg reload
}

set_tmux_colors() {
    sed -i --follow-symlinks -E "
    s/status-style.*/status-style \'fg=$bar_fg bg=$bar_bg\'/;
    s/pane-border-style.*/pane-border-style \'fg=$bar_bg bg=$bar_bg\'/;
    s/pane-active-border-style.*/pane-active-border-style \'fg=$bar_bg bg=$bar_bg\'/;
    s/popup-border-style.*/popup-border-style \'bg=$bar_bg fg=$bar_bg\'/
    " "$HOME/.tmux.conf"

    tmux source-file "$HOME/.tmux.conf"
}

set_xfce4_terminal_colors() {
    sed -i --follow-symlinks -E "
    s/ColorBackground=.*/ColorBackground=${theme[background]}/;
    s/ColorForeground=.*/ColorForeground=${theme[foreground]}/;
    s/ColorCursor=.*/ColorCursor=${theme[cursorColor]}/;
    s/ColorPalette=.*/ColorPalette=${theme[0]};${theme[1]};${theme[2]};${theme[3]};${theme[4]};${theme[5]};${theme[6]};${theme[7]};${theme[8]};${theme[9]};${theme[10]};${theme[11]};${theme[12]};${theme[13]};${theme[14]};${theme[15]}/
    " "$HOME/.config/xfce4/terminal/terminalrc"
}

set_X_colors() {
    xrdb -override << EOF
     *.background: ${theme[background]}
     *.foreground: ${theme[foreground]}
    *.cursorColor: ${theme[cursorColor]}
         *.color0: ${theme[0]}
         *.color1: ${theme[1]}
         *.color2: ${theme[2]}
         *.color3: ${theme[3]}
         *.color4: ${theme[4]}
         *.color5: ${theme[5]}
         *.color6: ${theme[6]}
         *.color7: ${theme[7]}
         *.color8: ${theme[8]}
         *.color9: ${theme[9]}
        *.color10: ${theme[10]}
        *.color11: ${theme[11]}
        *.color12: ${theme[12]}
        *.color13: ${theme[13]}
        *.color14: ${theme[14]}
        *.color15: ${theme[15]}
EOF

    xrdb -q > "$HOME/.Xresources"
}

main() {
    declare -n theme
    case "$1" in
        gruvbox)
            theme=theme_gruvbox
            vim_bg=dark
            vim_colorscheme=gruvbox
            bar_bg="#3c3836"
            bar_fg="#a89984"
            ;;
        papercolor)
            theme=theme_papercolor
            vim_bg=light
            vim_colorscheme=PaperColor
            bar_bg="#e4e4e4"
            bar_fg="${theme[foreground]}"
            ;;
        solarized)
            theme=theme_solarized
            vim_bg=dark
            vim_colorscheme=solarized
            bar_bg="#073642"
            bar_fg="${theme[foreground]}"
            ;;
        nord)
            theme=theme_nord
            vim_bg=dark
            vim_colorscheme=nord
            bar_bg="#3B4252"
            bar_fg="#D8DEE9"
            ;;
        acme)
            theme=theme_acme
            vim_bg=light
            vim_colorscheme=acme
            bar_bg="#eaffff"
            bar_fg="#000000"
            ;;
        onedark)
            theme=theme_onedark
            vim_bg=dark
            vim_colorscheme=onedark
            bar_bg="${theme[8]}"
            bar_fg="${theme[15]}"
            ;;
        rosepine)
            theme=theme_rosepine
            vim_bg=dark
            vim_colorscheme=rosepine
            bar_bg="${theme[8]}"
            bar_fg="${theme[15]}"
            ;;
        *) echo "usage: ${0##*/} <theme>" 1>&2 && exit 1
    esac

    set_X_colors
    set_vim_colors
    set_i3_colors
    set_tmux_colors
    set_xfce4_terminal_colors
}

main "$@"
