#!/bin/sh

set -e
session_name='gns3'
HOST="$1"
PORT="$2"
TITLE="$3"

new_session() { tmux new-session -d -s "${session_name}" ;}
attach_session() { tmux attach-session -t "${session_name}" ;}
has_session() { tmux has-session -t 'gns3' ;}
new_window() { tmux new-window -S -t 'gns3' -n "${TITLE}" "telnet ${HOST} ${PORT}" ;}

if ! has_session; then
    new_session
fi

if test $# = 3; then
    new_window
    exit
fi

attach_session
