#!/bin/sh

# what to do when opening new terminal..

Clients=$(tmux list-clients 2> /dev/null)
sessions=$(tmux list-sessions 2> /dev/null)
session_name="$1"

test -z "${sessions}" && exec tmux new-session
test -n "${session_name}" && exec tmux new-session -A -s "${session_name}"

if test -n "${sessions}"; then
    exec /bin/bash
fi
