#!/bin/sh

clipfile="/tmp/clip"
umask 066
test -f $clipfile && rm $clipfile
cat - > $clipfile

if test -n "$WAYLAND_DISPLAY"; then
    wl-copy < $clipfile
elif test -n "$DISPLAY"; then
    xclip -in -selection clipboard -rmlastnl < $clipfile || \
        xsel --input --clipboard < $clipfile
fi
