#!/bin/bash

# just do not do it this way: ':smile::sad:'. It wont work as expected
declare -A emojies=(
[smile]=🙂 [tear]=😢 [happy]=😃 [lol]=🤣 [hot]=🥵 [cool]=😎 [skull]=💀
[sad]=☹️  [cry]=😭 [think]=🤔 [xd]=😆 [cold]=🥶 [fire]=🔥 [ghost]=👻
[bot]=🤖 [cowboy]=🤠 [heart]=❤️  [celebrate]=🥳 [disappointed]=😞 [frog]=🐸
[mindblow]=🤯 [evil]=😈 [scared]=😱
#😵😗😟😚😪😳🤕😮🤩🤑😼🤥☺️😹🤬😈😤😃😫😽🥰🥸😉🙂😦😡☠️😬🤓😓😸😄🙁
#👺🤡👹😴😿😋😷😊🤤👾🥴😲🥺🤒😌🤧🤗😇😒👽😨😝😶😑🤣😖😛😅
#🎃😙🤫😥🤪😜😏🙀😰🧐🤢#😵💫😕😘🤨🤮😣🤭😯😁😾😔🥲😍😀😧
#❤️ 🩹😂🥱😻#😩😺👿😐😶🌫️🤐😠😮💨🙄
)

pattern=':([a-zA-Z]+):'

while read -r line; do
    if [[ ! $line =~ $pattern ]]; then
        printf '%s\n' "$line"
        continue
    fi

    for w in ${line}; do
        [[ $w =~ ${pattern} ]] || continue
        k=${BASH_REMATCH[1]}
        v=${emojies[$k]:-":$k:"}
        line="${line//:$k:/$v}"
    done
    printf '%s\n' "$line"
done < ${1:-/dev/stdin}
