#!/bin/sh

# rename tmux window, works with arabic as well

trw() {
    if command -v fribidi >/dev/null 2>&1; then
        title="$(printf '%s' "$1" | fribidi --nopad)"
    else
        title="$1"
    fi

    tmux rename-window "$title"
}

if test $# == 0; then
    read -r line
else
    line="$*"
fi

trw "$line"
