#!/bin/sh
# shellcheck disable=SC3043
# set the colors of tmux windows :)

dark() {
	bg="#000000" fg="#cccccc"
	c0="#000000" c1="#ff5555" c2="#55ff55" c3="#ffff55" c4="#5555ff" c5="#ff55ff" c6="#55ffff" c7="#bbbbbb"
	c8="#555555" c9="#ff5555" c10="#55ff55" c11="#ffff55" c12="#5555ff" c13="#ff55ff" c14="#55ffff" c15="#ffffff"
}; themes="$themes dark"

light() {
	bg="#ffffff" fg="#000000"
	c0="#000000" c1="#c91b00" c2="#00c200" c3="#c7c400" c4="#0225c7" c5="#ca30c7" c6="#00c5c7" c7="#c7c7c7"
	c8="#686868" c9="#c91b00" c10="#00c200" c11="#c7c400" c12="#0225c7" c13="#ca30c7" c14="#00c5c7" c15="#ffffff"
	#c8="#686868" c9="#ff6e67" c10="#5ffa68" c11="#fffc67" c12="#6871ff" c13="#ff77ff" c14="#60fdff" c15="#ffffff"
}; themes="$themes light"

japanesque() {
	bg="#1e1e1e" fg="#f7f6ec"
	c0="#343935" c1="#cf3f61" c2="#7bb75b" c3="#e9b32a" c4="#4c9ad4" c5="#a57fc4" c6="#389aad" c7="#fafaf6"
	c8="#595b59" c9="#d18fa6" c10="#767f2c" c11="#78592f" c12="#135979" c13="#604291" c14="#76bbca" c15="#b2b5ae"
}; themes="$themes japanesque"

solarized() {
	bg="#001e27" fg="#9cc2c3"
	c0="#002831" c1="#d11c24" c2="#6cbe6c" c3="#a57706" c4="#2176c7" c5="#c61c6f" c6="#259286" c7="#eae3cb"
	c8="#006488" c9="#f5163b" c10="#51ef84" c11="#b27e28" c12="#178ec8" c13="#e24d8e" c14="#00b39e" c15="#fcf4dc"
}; themes="$themes solarized"

setcolors() {
	tmux set -gw window-style "bg=$bg fg=$fg" \; \
		set -gw pane-colours "$c0 $c1 $c2 $c3 $c4 $c5 $c6 $c7 $c8 $c9 $c10 $c11 $c12 $c13 $c14 $c15" \; \
		set -gw popup-style "bg=$bg fg=$fg" \; \
		set -gw popup-border-style "bg=$bg fg=cyan" \; \
		set -gw pane-border-style "fg=brightblack bg=$bg" \; \
		set -gw pane-active-border-style "fg=brightblack bg=$bg"

}

resetcolors() {
	tmux set -ugw window-style \; \
		set -ugw pane-colours \; \
		set -ugw popup-style \; \
		set -gw popup-border-style "bg=default fg=cyan" \; \
		set -gw pane-border-style "fg=brightblack bg=default" \; \
		set -gw pane-active-border-style "fg=brightblack bg=default"
}

list_themes() {
	set -- $themes
	local IFS=\|
	echo "${0##*/} $*"
}

main() {
	local t="$1"

	test "$t" = "reset" && {
		resetcolors
		exit 0
	}

	for tt in $themes; do
		test "$tt" = "$t" && {
			"$t"
			setcolors
			exit 0
		}
	done

	list_themes
	exit 1
}

main "$@"
