#!/bin/bash

urldecode() {
    str="$*"
    str="${str//+/ }"
    str="${str//%/\\x}"
    printf "$str"
}

if [[ $1 == "-s" ]]; then
    shift
    urldecode "$*"
    exit
fi

while IFS= read line; do
    urldecode "$line"
done < "${1:-/dev/stdin}"
