#!/bin/bash

urlencode() {
    local str="$*"
    local len="${#str}"
    local str_encoded=
    local c_encoded=
    local p c

    for ((p = 0; p < len; p++)); do
        c="${str:$p:1}"
        c_encoded="$c"
        if [[ $c != [-_.~0-9a-zA-Z] ]]; then
            printf -v c_encoded '%%%02x' "'$c'"
        fi
        str_encoded+="$c_encoded"
    done

    printf '%s\n' "$str_encoded"
}

while IFS= read line; do
    urlencode "$line"
done < "${1:-/dev/stdin}"
