#!/bin/sh

# edit dotfiles quickly

# global variable, does not look like a good idea.
Dir="${DOTFILES}"

if [ ! -x "${Dir}" ]; then
    echo "$Dir does not exist." 2>&1
    exit 1
fi

Ignore="
! -path *.git*
! -path *vim/plugged*
! -path *tmux/plugins*
"
Files="$(find ${Dir} ${Ignore} -type f)"

if [ -n "$1" ]; then
    # we can make fzf act as grep  with the -f or --filter option
    # sometimes its better because we would search in a fuzzy way
    # like:i3 config
    File="$(printf "%s\n" ${Files} | fzf --filter="$*" | head -n1)"
fi

if [ -z "${File}" ]; then
    # fzf exit with 130 if interuptted with C-c or ESC
    File=$(printf '%s\n' ${Files} | fzf) || exit 0
fi

[ -n "${File}" ] && exec vi "${File}"
