#!/bin/bash

if (($# < 4)); then
    echo "${0##*/} Start End Src Dst"
    exit 1
fi

Start="$1"
End="$2"
Src="$3"
Dst="$4"
youtube_dl="yt-dlp --no-playlist -f best --get-url "$Src""
[[ "$Src" = *www.* ]] && Src="$($youtube_dl)"
ffmpeg -ss $Start -to $End -i "$Src" -codec copy "$Dst"
