#!/bin/sh

# wall get, set.

wallpaper="$HOME/.config/wallpaper.jpg"
wallpapers="$HOME/.config/wallpapers"

if [ -n "$1" ]; then
    case "$1" in
        get)
            url="$2"
            imagepath="${url##*/}"
            if wget "${url}" -P "${wallpapers}"; then
                imagepath="${wallpapers}/${imagepath}"
            fi
            ;;
        -r|random)
            imagepath="$(find "${wallpapers}" | shuf -n1)"
            ;;
        -o)
            sxiv "${wallpapers}"
            exit 0
            ;;
        *)
            imagepath="$1" ;;
    esac
    # check if the supplied arg is an image
    filetype="$(file --mime-type --brief "${imagepath}")"
    case "${filetype}" in
        *image*) cp "${imagepath}" ${wallpaper} ;;
        *) echo "not jpeg." && exit 1
    esac
fi

hsetroot -fill "${wallpaper}" > /dev/null
