#!/bin/sh

# wall get, set.

wallpaper="$HOME/.config/wallpaper.jpg"
wallpapers="$HOME/.config/wallpapers"

_hash_image() {
    imagehash=$(md5sum "$1")
    imagehash=${imagehash%% *}
}

_is_image() {
    filetype="$(file --mime-type --brief "$1")"
    case "${filetype}" in
        *image*) return 0;;
        *) echo "not jpeg." 2>&1 && return 1;;
    esac
}

_set_as_wallpaper() {
    cp "$1" "${wallpaper}"
}

get_image() {
    url="$1"
    tempname="$(mktemp)"
    wget -q "${url}" -O "${tempname}" || exit 1
    if _is_image "${tempname}"; then
        _hash_image "${tempname}"
        imagepath="${wallpapers}/${imagehash}.jpg"
        mv "${tempname}" "${imagepath}"
    else
        rm "${tempname}"
    fi
}

if test -n "$1"; then
    case "$1" in
        get) get_image "$2" ;;
        -r|random) imagepath="$(shuf -n1 -e ${wallpapers}/*)" ;;
        -o|open) sxiv "${wallpapers}"; exit 0 ;;
        *) imagepath="$1" ;;
    esac

    if _is_image "${imagepath}"; then
        _set_as_wallpaper "${imagepath}"
    else
        echo "${imagepath} is not an image" 2>&1
    fi
fi

hsetroot -full "${wallpaper}" > /dev/null
