#!/bin/sh

today_time="$(date +%s)"
from_time="$(date -d "$1" +%s)"
to_time="$(date -d "$2 week" +%s)"

# get the difference between today and from time
diff_today_from=$((from_time - today_time))

# add it up
to_time=$((to_time + diff_today_from))

# get dates
from_date="$(date -d @${from_time} '+%b %d')"
to_date="$(date -d @${to_time} '+%b %d')"

echo "${from_date} - ${to_date}"
