#!/bin/sh

_prompt() {
    local reply
    reply="$(printf '%s\n' "$@" | dmenu -p "format:")"
    echo "${reply}"
}

choose_format() {
    local opts="1080 720 480 360 240 144 audio"
    format="$(_prompt ${opts})"

    case "${format}" in
        audio) ytdl_format="bestaudio";;
        *) ytdl_format="bestvideo[height<=${format}]+bestaudio/best"
    esac
}

get_description() {
    mkdir /tmp/youtube --mode 700 2>/dev/null
    video_title="$(yt-dlp --print title "$1" 2>/dev/null)"
    yt-dlp --print description "$1" > /tmp/youtube/"${video_title}".txt
}

_play() {
    exec mpv --ytdl-format="$1" "$2"
}

main() {
    url="$1"
    if test -z "$1"; then
        echo "$0 <url>"
        exit 1
    fi

    choose_format
    get_description "${url}"
    _play "${ytdl_format}" "${url}"
}

# ---

main "$@"
